// LearnShareCar/src/components/Navbar.vue
<template>
    <div class="w3-top">
        <ul class="w3-navbar w3-theme-d2 w3-left-align w3-large">
            <li class="w3-hide-small w3-dropdown-hover">
                <a href="#" class="w3-padding-large w3-hover-white" title="Notifications">Administration</span></a>
                <div class="w3-dropdown-content w3-white w3-card-4">
                    <a href="#">add a new car</a>
                    <a href="#">Add new availibility</a>
                </div>
            </li>
        </ul>
    </div>
</template>

<script>
export default {
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>

// learnsharecarA2/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'app-navbar',
  templateUrl: 'navbar.component.html',
  styleUrls: ['navbar.component.css']
})
export class NavbarComponent {

  constructor() { }


}

<div class="w3-top">
  <ul class="w3-navbar w3-theme-d2 w3-left-align w3-large">
      <li class="w3-hide-small w3-dropdown-hover">
          <a href="#" class="w3-padding-large w3-hover-white" title="Notifications">Administration</a>
          <div class="w3-dropdown-content w3-white w3-card-4">
              <a href="#">add a new car</a>
              <a href="#">Add new availibility</a>
          </div>
      </li>
  </ul>
</div>
